repos:
  # --- Форматирование и стиль ---
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile=black"]

  # --- Локальный хук: пересоздание .secrets.baseline ---
  - repo: local
    hooks:
      - id: update-detect-secrets-baseline
        name: 🔄 Обновление detect-secrets baseline
        entry: >
          bash -c '
            echo "🔍 Пересоздание .secrets.baseline...";
            files=$(find . -type f \
              -not -path "*/.git/*" \
              -not -path "*/.venv/*" \
              -not -path "*/__pycache__/*" \
              -not -path "*/.mypy_cache/*" \
              -not -path "*/.pytest_cache/*" \
              -not -path "*/.idea/*" \
              -not -name ".secrets.baseline" \
              -not -name ".env" \
              -not -name "poetry.lock");
            detect-secrets scan --disable-filter ALL $files > .secrets.baseline;
            if [ $? -eq 0 ] && [ -s .secrets.baseline ]; then
              echo "✅ Baseline успешно создан.";
            else
              echo "⚠️ Baseline пуст или не создан!";
              exit 1;
            fi
          '
        language: system
        pass_filenames: false

  # --- Проверка: baseline не должен содержать секреты ---
  - repo: local
    hooks:
      - id: validate-no-secrets
        name: "❌ Проверка: baseline не должен содержать секретов"
        entry: >
          bash -c '
            if grep -q "hashed_secret" .secrets.baseline; then
              echo "🚨 Найдены секреты в коде! Удали или замаскируй их перед коммитом.";
              echo "📄 Список найденных секретов:";
              jq -r "
                .results | to_entries[] |
                \"📁 Файл: \(.key)\" +
                (.value[] |
                  \"  🔐 Тип: \(.type)\\n  📍 Строка: \(.line_number)\\n\"
                )
              " .secrets.baseline;
              exit 1;
            else
              echo \"✅ Секреты не найдены.\";
            fi
          '
        language: system
        pass_filenames: false
        always_run: true

  # --- Проверка секретов по baseline ---
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - "--baseline"
          - ".secrets.baseline"
          - "--exclude-files"
          - ".*\\.venv/.*|.*__pycache__/.*|.*\\.mypy_cache/.*|.*\\.pytest_cache/.*|.*\\.env"
        always_run: true
        pass_filenames: true

  # --- Типизация ---
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy

  # --- Общие хуки ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  # --- Юнит-тесты ---
  - repo: local
    hooks:
      - id: pytest
        name: 🧪 Pytest before commit
        entry: pytest -q
        language: system
        pass_filenames: false
