name: 🧪 Run Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # --- 1️⃣ Клонируем проект ---
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      # --- 2️⃣ Устанавливаем Python ---
      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # --- 3️⃣ Устанавливаем зависимости ---
      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # --- 4️⃣ Устанавливаем Chrome для Selenium ---
      - name: 🌐 Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      # --- 5️⃣ Запускаем тесты + покрытие ---
      - name: 🚀 Run tests with coverage
        env:
          # 🔹 SMTP-секреты (создаются твоим скриптом)
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          # 🔹 Chrome для UI-тестов
          CHROME_BIN: /usr/bin/chromium-browser
        run: |
          echo "🚀 Запуск pytest с отчётом о покрытии"
          PYTHONPATH=. pytest -v --cov=app --cov-report=json --cov-report=term-missing --cov-fail-under=85

      # --- 6️⃣ Загружаем скриншот, если Selenium падал ---
      - name: 📸 Upload Selenium screenshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-screenshot
          path: screenshot.png
          if-no-files-found: ignore

      # --- 7️⃣ Загружаем отчёт о покрытии ---
      - name: 📊 Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          if-no-files-found: ignore
